version: "2"
services:
  # mysql
  mysql:
    build: mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/iib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
  # redis
  redis:
    image: redis:3.0.5
  # memcached
  memcached:
    image: memcached
  # nginx
  nginx-php:
    build: ./nginx-php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./log/nginx/:/var/log/nginx/
      - ./log/php-fpm/:/var/log/php-fpm/
      - ./src/:/var/www/html/
      - ./self-cert/:/var/www/self-cert/
    environment:
      TZ: "Asia/Tokyo"
    links:
      - mysql
      - redis
      - memcached
